---
- name: Configure webserver with nginx
  hosts: ungrouped
  become: true
  tasks:
    - name: create directories if they don't exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled
        - /usr/share/nginx/html
    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        update_cache: true
    - name: Copy nginx config file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
    - name: Enable configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: Copy home page template
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
